import { TFile, Notice, normalizePath } from "obsidian";
import HormePlugin from "../../main";
import { HormeErrorModal } from "../modals/HormeErrorModal";
import {
  compressEmbedding,
  cosineSimilarityFloatInt8,
  cosineSimilarityInt8,
  decompressEmbeddingToInt8,
  getModelPrefixes,
  quantizeEmbeddingToInt8
} from "../utils/VectorUtils";
import { OllamaProvider } from "../providers/OllamaProvider";
import { LmStudioProvider } from "../providers/LmStudioProvider";
import { asArray, asNumberArray, errorToMessage, getNumberProp, getRecordProp, getStringProp } from "../utils/TypeGuards";

interface IndexEntry {
  path: string;
  chunkStart: number;
  chunkEnd: number;
  embedding: Int8Array | string;
  mtime: number;
  summaryText?: string;
  tagsText?: string;
  headingPath?: string;
}


const STOP_WORDS = new Set([
  "ayudame", "encontrar", "podrias", "busca", "encuentra", "dime", "sobre", "hablame", "tienes", "algo", "articulo", "nota", "notas", "vault", "boveda", "mi", "mis",
  "the", "and", "for", "with", "from", "that", "this", "these", "those", "about", "find", "help", "note", "search", "does", "what", "where", "when", "how", "why", "who", "which",
  "un", "una", "unos", "unas", "el", "la", "los", "las", "en", "con", "por", "para", "que", "del", "al", "was", "were", "been", "have", "has", "had",
  "pais", "paises", "estilos", "generos", "periodos", "estructuras"
]);

export class VaultIndexer {
  private plugin: HormePlugin;
  public index: IndexEntry[] = [];
  private pathIndex: Map<string, IndexEntry[]> = new Map();
  public indexedModel: string = "";
  public loadWasPartial: boolean = false;
  private isSaving: boolean = false;
  private pendingSave: boolean = false;
  private lastShardSaveTime: number = 0;
  private indexPath: string;
  // Cache of Spanish tag string → bilingual tag string.
  // Built during indexing to avoid redundant LLM calls for notes sharing the same tags.
  // Cleared when the plugin unloads (in-memory only — intentionally not persisted).
  private tagTranslationCache: Map<string, string> = new Map();
  private hasReportedEmptyTagTranslationModel = false;

  /** O(1) lookup of entries by path */
  private getEntriesForPath(path: string): IndexEntry[] {
    return this.pathIndex.get(path) || [];
  }

  /** Removes all entries for a given path from both the flat array and the Map */
  public removeEntriesForPath(path: string): void {
    const existing = this.pathIndex.get(path);
    if (!existing || existing.length === 0) return;
    const pathSet = new Set(existing);

    let writeIndex = 0;
    for (let i = 0; i < this.index.length; i++) {
      if (!pathSet.has(this.index[i])) {
        this.index[writeIndex++] = this.index[i];
      }
    }
    this.index.length = writeIndex;

    this.pathIndex.delete(path);
  }

  /** Adds entries and updates the Map */
  private addEntries(entries: IndexEntry[]): void {
    for (const entry of entries) {
      this.index.push(entry);
      const arr = this.pathIndex.get(entry.path);
      if (arr) arr.push(entry);
      else this.pathIndex.set(entry.path, [entry]);
    }
  }

  /** Clears both the flat array and the Map */
  private clearIndex(): void {
    this.index = [];
    this.pathIndex.clear();
  }

  /** Rebuilds the pathIndex Map from the flat array (used after deserialization) */
  private rebuildPathIndex(): void {
    this.pathIndex.clear();
    for (const entry of this.index) {
      const arr = this.pathIndex.get(entry.path);
      if (arr) arr.push(entry);
      else this.pathIndex.set(entry.path, [entry]);
    }
  }

  private getCachePath(): string {
    const configDir = this.plugin.app.vault.configDir;
    return normalizePath(`${configDir}/plugins/${this.plugin.manifest.id}/Tag History/translations.json`);
  }

  async loadTagCache(): Promise<void> {
    const path = this.getCachePath();
    const adapter = this.plugin.app.vault.adapter;
    if (await adapter.exists(path)) {
      try {
        const data = await adapter.read(path);
        const parsed = JSON.parse(data);
        this.tagTranslationCache = new Map(Object.entries(parsed));
      } catch (e) {
        console.error("Horme Brain: Failed to parse Tag History", e);
        this.tagTranslationCache = new Map();
      }
    } else {
      this.tagTranslationCache = new Map();
    }
  }

  async saveTagCache(): Promise<void> {
    const path = this.getCachePath();
    const adapter = this.plugin.app.vault.adapter;
    const folderPath = path.substring(0, path.lastIndexOf('/'));

    if (!(await adapter.exists(folderPath))) {
      await adapter.mkdir(folderPath);
    }

    const obj = Object.fromEntries(this.tagTranslationCache);
    await adapter.write(path, JSON.stringify(obj, null, 2));
  }

  constructor(plugin: HormePlugin) {
    this.plugin = plugin;

    // ONE-TIME SANITISATION MIGRATION:
    // Wipes corrupted tags generated by the old regex parser in previous versions.
    if (!this.plugin.settings.tagCacheSanitised) {
      console.log("Horme Brain: Performing one-time sanitisation of tag translation cache.");
      this.plugin.settings.tagCacheSanitised = true;
      void this.plugin.saveSettings();
    }

    // Load persisted tag translations into RAM
    this.tagTranslationCache = new Map(); // Will be populated async via loadTagCache()
    // Explicitly resolve the plugin directory relative to the vault root
    const configDir = this.plugin.app.vault.configDir;
    this.indexPath = normalizePath(`${configDir}/plugins/${this.plugin.manifest.id}/Vault Index/vault-index.json`);
    console.log(`Horme Brain: Initializing index at ${this.indexPath}`);
    void this.loadIndex();

    // Wipe index if embedding model changes while plugin is running
    this.plugin.onSettingsChange(() => {
      const current = this.plugin.settings.ragEmbeddingModel;
      if (this.indexedModel && this.indexedModel !== current) {
        console.log(`Horme Brain: Model changed to ${current}. Clearing in-memory index and shard files.`);
        this.clearIndex();
        this.indexedModel = current;
        this.deleteAllShards().catch((e: unknown) => {
          this.plugin.diagnosticService.report("Vault Brain", `Failed to delete stale shard files: ${errorToMessage(e)}`);
        });
        new Notice("Vault Brain: Embedding model changed. Index cleared — please rebuild.");
      }
    });
  }

  private readonly SHARD_SIZE = 5000;

  private getShardPath(shardIndex: number): string {
    const configDir = this.plugin.app.vault.configDir;
    return normalizePath(
      `${configDir}/plugins/${this.plugin.manifest.id}/Vault Index/vault-index-shard-${String(shardIndex).padStart(3, "0")}.json`
    );
  }

  private async loadIndex(): Promise<void> {
    try {
      await this.loadTagCache();
      this.plugin.setIndexingStatus("Loading Vault Index...");
      // New sharded format: look for the first shard file
      if (await this.plugin.app.vault.adapter.exists(this.getShardPath(0))) {
        await this.loadShardedIndex();
        return;
      }

      // Old monolithic format: migrate and delete the old file
      if (await this.plugin.app.vault.adapter.exists(this.indexPath)) {
        console.log("Horme Brain: Migrating from monolithic to sharded index...");
        const data = await this.plugin.app.vault.adapter.read(this.indexPath);
        const parsed: unknown = JSON.parse(data);

        if (Array.isArray(parsed)) {
          // Very old format — wipe
          this.clearIndex();
          this.indexedModel = "";
        } else {
          this.indexedModel = getStringProp(parsed, "model") ?? "";
          this.index = this.parseEntries(getRecordProp(parsed, "entries"));
          this.rebuildPathIndex();
          const currentModel = this.plugin.settings.ragEmbeddingModel;
          if (this.indexedModel !== currentModel) {
            this.clearIndex();
            this.indexedModel = currentModel;
          }
        }

        // Save in new sharded format and remove the old monolithic file
        await this.saveIndex();
        await this.plugin.app.vault.adapter.remove(this.indexPath);
        console.log(`Horme Brain: Migration complete. ${this.index.length} entries across ${Math.ceil(this.index.length / this.SHARD_SIZE)} shards.`);
        return;
      }

      console.log("Horme Brain: No existing index found.");
    } catch (e: unknown) {
      this.plugin.diagnosticService.report("Vault Brain", `Critical load failure: ${errorToMessage(e)}`);
      this.clearIndex();
    } finally {
      this.isLoaded = true;
      this.plugin.setIndexingStatus(null);
    }
  }

  private parseEntries(entriesUnknown: unknown): IndexEntry[] {
    const entries = asArray(entriesUnknown) ?? [];
    const out: IndexEntry[] = [];
    for (const e of entries) {
      const path = getStringProp(e, "path");
      const chunkStart = getNumberProp(e, "chunkStart");
      const chunkEnd = getNumberProp(e, "chunkEnd");
      const mtime = getNumberProp(e, "mtime");
      if (!path || chunkStart === undefined || chunkEnd === undefined || mtime === undefined) continue;

      const embeddingUnknown = getRecordProp(e, "embedding");
      let embedding: Int8Array | string = new Int8Array();

      // RESTORED: Decompress into binary memory immediately on load
      if (typeof embeddingUnknown === "string") embedding = decompressEmbeddingToInt8(embeddingUnknown);
      else {
        const embArr = asNumberArray(embeddingUnknown);
        if (embArr) embedding = quantizeEmbeddingToInt8(embArr);
      }

      const summaryText = getStringProp(e, "summaryText");
      const tagsText = getStringProp(e, "tagsText");
      const headingPath = getStringProp(e, "headingPath");

      out.push({
        path,
        chunkStart,
        chunkEnd,
        embedding,
        mtime,
        ...(summaryText ? { summaryText } : {}),
        ...(tagsText ? { tagsText } : {}),
        ...(headingPath ? { headingPath } : {}),
      });
    }
    return out;
  }

  private async loadShardedIndex(): Promise<void> {
    this.clearIndex();
    let shardIndex = 0;
    let partialLoadFailed = false;
    let failedShardInfo: { shard: number; path: string } | null = null;

    while (true) {
      const path = this.getShardPath(shardIndex);
      if (!(await this.plugin.app.vault.adapter.exists(path))) break;

      this.plugin.setIndexingStatus(`Loading Brain: Shard ${shardIndex}...`);

      try {
        const data = await this.plugin.app.vault.adapter.read(path);
        const parsed: unknown = JSON.parse(data);

        // Validate model on the first shard only
        if (shardIndex === 0) {
          this.indexedModel = getStringProp(parsed, "model") ?? "";
          const currentModel = this.plugin.settings.ragEmbeddingModel;
          if (this.indexedModel !== currentModel) {
            console.log(`Horme Brain: Embedding model changed (${this.indexedModel} → ${currentModel}). Wiping all shards.`);
            this.clearIndex();
            this.indexedModel = currentModel;
            await this.deleteAllShards();
            return;
          }
        }

        const decompressed = this.parseEntries(getRecordProp(parsed, "entries"));
        // Use a safe concat to avoid "Maximum call stack size exceeded" errors on large vaults
        this.index = this.index.concat(decompressed);
      } catch (e: unknown) {
        this.plugin.diagnosticService.report("Vault Brain", `Failed to read index shard ${shardIndex}: ${errorToMessage(e)}`);
        partialLoadFailed = true;
        failedShardInfo = { shard: shardIndex, path };
        break;
      }

      shardIndex++;
    }

    if (partialLoadFailed && failedShardInfo) {
      this.loadWasPartial = true;
      this.indexedModel = "";
      this.clearIndex();

      const errorMsg = `The Vault Brain index failed to load completely because shard ${failedShardInfo.shard} was corrupted or unreadable.\n\nPath: ${failedShardInfo.path}\n\nTo prevent data loss or silently operating on truncated/corrupted search indexes, the in-memory index has been cleared. Please perform a full rebuild of the Vault Index to restore search functionality.`;
      
      new HormeErrorModal(
        this.plugin.app,
        "Vault Index Load Failure",
        errorMsg
      ).open();
      
      return;
    }

    // Reset flag upon a fully successful load
    this.loadWasPartial = false;

    this.rebuildPathIndex();
    console.log(`Horme Brain: Loaded ${this.index.length} entries from ${shardIndex} shards (model: ${this.indexedModel}).`);
  }

  private async saveIndex(): Promise<void> {
    if (this.loadWasPartial) {
      const errMsg = "Refusing to save index because the last index load was partial (shard failure). Saving now would corrupt/truncate the stored index.";
      this.plugin.diagnosticService.report("Vault Brain", errMsg, "error");
      console.error(`Horme Brain: ${errMsg}`);
      return;
    }

    if (this.isSaving) {
      this.pendingSave = true;
      return;
    }

    this.isSaving = true;

    try {
      try {
        const adapter = this.plugin.app.vault.adapter;
        const configDir = this.plugin.app.vault.configDir;
        const folderPath = normalizePath(`${configDir}/plugins/${this.plugin.manifest.id}/Vault Index`);
        if (!(await adapter.exists(folderPath))) await adapter.mkdir(folderPath);

        const currentModel = this.plugin.settings.ragEmbeddingModel;
        const totalShards = Math.max(1, Math.ceil(this.index.length / this.SHARD_SIZE));

        // ── Phase 1: Write all shards to temporary files ──
        // If the process crashes here, only .tmp files are affected;
        // the previous valid shards remain untouched on disk.
        const tmpPaths: string[] = [];
        const finalPaths: string[] = [];

        for (let i = 0; i < totalShards; i++) {
          const shardEntries = this.index
            .slice(i * this.SHARD_SIZE, (i + 1) * this.SHARD_SIZE)
            .map(e => ({
              path: e.path,
              chunkStart: e.chunkStart,
              chunkEnd: e.chunkEnd,
              embedding: typeof e.embedding === "string"
                ? e.embedding
                : compressEmbedding(e.embedding),
              mtime: e.mtime,
              ...(e.summaryText ? { summaryText: e.summaryText } : {}),
              ...(e.tagsText ? { tagsText: e.tagsText } : {}),
              ...(e.headingPath ? { headingPath: e.headingPath } : {}),
            }));

          const shardData = JSON.stringify({
            model: currentModel,
            shard: i,
            totalShards,
            entries: shardEntries,
          });

          const finalPath = this.getShardPath(i);
          const tmpPath = finalPath + ".tmp";
          await adapter.write(tmpPath, shardData);
          tmpPaths.push(tmpPath);
          finalPaths.push(finalPath);
        }

        // ── Phase 2: Atomic rename pass ──
        // Each rename replaces the old shard with the new one.
        // If we crash here, we get either the old shard (safe) or a missing
        // shard (caught by partialLoadFailed on next startup).
        for (let i = 0; i < tmpPaths.length; i++) {
          // adapter.rename() does not overwrite on all platforms, so remove first
          if (await adapter.exists(finalPaths[i])) {
            await adapter.remove(finalPaths[i]);
          }
          await adapter.rename(tmpPaths[i], finalPaths[i]);
        }

        // ── Phase 3: Clean up stale shards from a previously larger index ──
        for (let i = totalShards; ; i++) {
          const stalePath = this.getShardPath(i);
          if (await adapter.exists(stalePath)) {
            await adapter.remove(stalePath);
          } else {
            break;
          }
        }

        // Clean up any orphaned .tmp files from a previously interrupted save
        const listed = await adapter.list(folderPath);
        for (const f of listed.files) {
          if (f.endsWith(".tmp")) {
            await adapter.remove(f);
          }
        }

        this.indexedModel = currentModel;
      } catch (e: unknown) {
        this.plugin.diagnosticService.report("Vault Brain", `Critical save failure: ${errorToMessage(e)}`);
        new HormeErrorModal(
          this.plugin.app,
          "Vault Brain: Index save failed",
          "Horme could not save the vault index to disk. Indexing has been paused to prevent data loss.",
          String(e)
        ).open();
      }
    } finally {
      this.isSaving = false;
      if (this.pendingSave) {
        this.pendingSave = false;
        void this.saveIndex().catch((e: unknown) => {
          this.plugin.diagnosticService.report("Vault Brain", `Deferred save failed: ${errorToMessage(e)}`);
        });
      }
    }
  }

  private getVaultIndexFolderPath(): string {
    const configDir = this.plugin.app.vault.configDir;
    return normalizePath(`${configDir}/plugins/${this.plugin.manifest.id}/Vault Index`);
  }

  async hasBuiltIndex(): Promise<boolean> {
    if (this.index.length > 0) return true;
    const adapter = this.plugin.app.vault.adapter;

    try {
      if (await adapter.exists(this.getShardPath(0))) return true;
      if (await adapter.exists(this.indexPath)) return true;
      return false;
    } catch {
      return false;
    }
  }

  private async deleteAllShards(): Promise<number> {
    const adapter = this.plugin.app.vault.adapter;
    const folderPath = this.getVaultIndexFolderPath();
    if (!(await adapter.exists(folderPath))) return 0;

    const listed = await adapter.list(folderPath);
    const shardFiles = listed.files.filter((path) => /vault-index-shard-\d+\.json$/i.test(path));

    for (const path of shardFiles) {
      await adapter.remove(path);
    }
    return shardFiles.length;
  }

  async deleteIndex(): Promise<"deleted" | "missing" | "blocked"> {
    if (this.isIndexing || this.isProcessingQueue) {
      new Notice("Vault Brain: Please wait for indexing to finish before deleting the index.");
      return "blocked";
    }

    try {
      const adapter = this.plugin.app.vault.adapter;
      const hadInMemory = this.index.length > 0;
      const hadLegacy = await adapter.exists(this.indexPath);
      const removedShardCount = await this.deleteAllShards();

      if (hadLegacy) {
        await adapter.remove(this.indexPath);
      }

      this.indexingQueue = [];
      this.clearIndex();
      this.tagTranslationCache.clear();
      const cachePath = this.getCachePath();
      if (await adapter.exists(cachePath)) {
        await adapter.remove(cachePath);
      }
      this.indexedModel = "";
      this.loadWasPartial = false;
      this.plugin.settings.indexStatus = "Not built";
      await this.plugin.saveSettings();
      this.plugin.setIndexingStatus(null);

      if (hadInMemory || hadLegacy || removedShardCount > 0) {
        this.plugin.diagnosticService.report("Vault Brain", "Vault index deleted by user.", "info");
        return "deleted";
      }
      this.plugin.diagnosticService.report("Vault Brain", "Delete requested, but no vault index was found.", "info");
      return "missing";
    } catch (e: unknown) {
      this.plugin.diagnosticService.report("Vault Brain", `Failed to delete index: ${errorToMessage(e)}`);
      throw e instanceof Error ? e : new Error(errorToMessage(e));
    }
  }

  /**
   * Best-effort save triggered on plugin unload.
   * Fire-and-forget — Electron gives normal closes enough time to complete.
   */
  flush(): void {
    if (this.index.length === 0) return;
    if (!this.isIndexing && !this.isProcessingQueue) return;
    console.log("Horme Brain: Obsidian closing mid-index — flushing progress...");
    this.plugin.settings.indexStatus = "Interrupted — resume rebuild to continue";
    void this.plugin.saveSettings().catch(e => this.plugin.handleError(e, "Vault Brain"));
    this.saveIndex()
      .then(() => console.log("Horme Brain: Emergency flush complete."))
      .catch((e: unknown) => {
        console.error("Horme Brain: Emergency flush failed.", e);
        this.plugin.diagnosticService.report("Vault Brain", `Emergency flush failed: ${errorToMessage(e)}`);
      });
  }



  isIndexing = false;
  public isLoaded = false;

  /** Extracts all markdown headings with their character offsets */
  private extractHeadings(content: string): Array<{ level: number; text: string; offset: number }> {
    const headings: Array<{ level: number; text: string; offset: number }> = [];

    // Mask code blocks with spaces to preserve character offsets while hiding comments
    const maskedContent = content.replace(/```[\s\S]*?```/g, match => " ".repeat(match.length));

    const regex = /^(#{1,6})\s+(.+)$/gm;
    let match;
    while ((match = regex.exec(maskedContent)) !== null) {
      headings.push({ level: match[1].length, text: match[2].trim(), offset: match.index });
    }
    return headings;
  }

  /** Returns the heading hierarchy path at a given character offset */
  private getHeadingPathAtOffset(headings: Array<{ level: number; text: string; offset: number }>, offset: number): string {
    const stack: string[] = [];
    const levelStack: number[] = [];
    for (const h of headings) {
      if (h.offset > offset) break;
      while (levelStack.length > 0 && levelStack[levelStack.length - 1] >= h.level) {
        stack.pop();
        levelStack.pop();
      }
      stack.push(h.text);
      levelStack.push(h.level);
    }
    return stack.join(' > ');
  }

  /**
   * Splits a raw Obsidian tag into its path components and leaf value.
   *
   * Rule: the LAST slash-separated segment is always the leaf value.
   * All preceding segments are path/category components.
   * Underscores are converted to spaces in all segments.
   *
   * Examples:
   *   "#artistas_suizos"               → { path: [],                           leaf: "artistas suizos" }
   *   "#escritores/jorge_luis_borges"  → { path: ["escritores"],               leaf: "jorge luis borges" }
   *   "#arquitectura/estilos/eclect…"  → { path: ["arquitectura", "estilos"],  leaf: "eclecticismo" }
   *   "#arte/país/alemania"            → { path: ["arte", "país"],             leaf: "alemania" }
   */
  private splitTagHierarchy(raw: string): { path: string[]; leaf: string } {
    const stripped = raw.replace(/^#+/, "").trim();
    const segments = stripped
      .split("/")
      .map(s => s.replace(/_/g, " ").trim())
      .filter(s => s.length > 0);

    if (segments.length === 0) return { path: [], leaf: "" };
    if (segments.length === 1) return { path: [], leaf: segments[0] };

    return {
      path: segments.slice(0, segments.length - 1),
      leaf: segments[segments.length - 1]
    };
  }

  /**
   * Generic Spanish navigation words that appear as intermediate nodes
   * in the tag hierarchy. These are useless as keyword search terms because
   * they are present on every note in their domain category.
   * When a tag like #arquitectura/país is used as a standalone tag (making
   * "país" the leaf value), it contributes nothing to discriminating search.
   */
  private static readonly GENERIC_TAG_NODES = new Set([
    "país", "países", "estilos", "géneros", "períodos", "estructuras",
    "región", "regiones", "tipo", "tipos", "categoría", "categorías"
  ]);

  private extractTagValues(raw: unknown): string[] {
    if (raw == null) return [];

    if (Array.isArray(raw)) {
      const out: string[] = [];
      for (const item of raw) out.push(...this.extractTagValues(item));
      return out;
    }

    if (typeof raw === "string") {
      const trimmed = raw.trim();
      if (!trimmed) return [];

      const bracketArray = trimmed.match(/^\[(.*)\]$/);
      const normalized = bracketArray ? bracketArray[1] : trimmed;
      return normalized
        .split(",")
        .map((v) => v.trim().replace(/^["']|["']$/g, ""))
        .filter((v) => v.length > 0);
    }

    return [];
  }

  /**
   * Collects tags for shadow-tagging from metadata cache (inline + YAML),
   * with frontmatter/raw-text fallbacks when cache is incomplete.
   */
  private collectShadowTags(
    content: string,
    file: TFile
  ): string[] {
    const rawTags: string[] = [];
    const add = (value: string) => {
      if (value && value.trim()) rawTags.push(value.trim());
    };

    const cache = this.plugin.app.metadataCache.getFileCache(file);
    if (cache?.tags) {
      for (const t of cache.tags) add(t.tag);
    }

    const frontmatter = cache?.frontmatter as Record<string, unknown> | undefined;
    if (frontmatter) {
      for (const tag of this.extractTagValues(frontmatter.tags)) add(tag);
      for (const tag of this.extractTagValues(frontmatter.tag)) add(tag);
    }

    const inlineTagRegex = /(^|\s)#([^\s#[\]{}()<>"',.!?;]+)/gm;
    let match: RegExpExecArray | null;
    while ((match = inlineTagRegex.exec(content)) !== null) {
      add(match[2]);
    }

    const uniqueTerms = new Set<string>();

    for (const raw of rawTags) {
      const { path, leaf } = this.splitTagHierarchy(raw);

      if (leaf && !VaultIndexer.GENERIC_TAG_NODES.has(leaf.toLowerCase())) {
        uniqueTerms.add(leaf);
      }

      for (const p of path) {
        if (p && !VaultIndexer.GENERIC_TAG_NODES.has(p.toLowerCase())) {
          uniqueTerms.add(p);
        }
      }
    }

    return Array.from(uniqueTerms).sort((a, b) => a.localeCompare(b, undefined, { sensitivity: "base" }));
  }

  private async preTranslateTags(files: TFile[]) {
    if (!this.plugin.settings.tagShadowingEnabled) return;

    this.plugin.setIndexingStatus("Scanning for new tags...");
    const uniqueTagInputs = new Set<string>();

    for (const file of files) {
      const content = await this.plugin.app.vault.cachedRead(file);
      const tags = this.collectShadowTags(content, file);

      for (const tag of tags) {
        if (!this.tagTranslationCache.has(tag)) {
          uniqueTagInputs.add(tag);
        }
      }
    }

    if (uniqueTagInputs.size > 0) {
      this.plugin.setIndexingStatus(`Pre-translating ${uniqueTagInputs.size} unique tags...`);
      const settings = this.plugin.settings;
      const model = settings.tagTranslationModel.trim();

      if (model) {
        const provider = settings.tagTranslationProvider === "lmstudio"
          ? new LmStudioProvider(settings.lmStudioUrl, settings.temperature, 500)
          : new OllamaProvider(settings.ollamaBaseUrl, settings.temperature, 500);

        const termsArray = Array.from(uniqueTagInputs);
        const CHUNK_SIZE = 8; // Safely throttled to eliminate model tracking fatigue
        let translatedCount = 0;
        let lastSaveTime = Date.now();

        for (let i = 0; i < termsArray.length; i += CHUNK_SIZE) {
          const chunk = termsArray.slice(i, i + CHUNK_SIZE);
          const chunkList = chunk.map((term, index) => `t${index} -> ${term}`).join("\n");

          try {
            const systemPrompt = `You are a mechanical, automated translation tool mapping Spanish items to British English.
Translate ONLY the values on the right side of the -> delimiter.

CRITICAL PROCESSING RULES:
1. NO REFUSALS: Act strictly as a data processor. Never censor, skip, or refuse explicit, sensitive, or controversial terms (e.g., "prostitución", "sexo", "zoofilia"). Translate them directly.
2. ANCHOR PRESERVATION: You MUST retain the exact token anchor identifier (e.g., t0 ->, t1 ->) on the left side of the line. Do not alter the index character or replace it with raw numbers.
3. DOMAIN ACCURACY:
   - "letras" -> letters
   - "gentilicios" -> demonyms
   - "concept" -> concept
4. LINGUISTIC TERMS: If a term has no translation (e.g., "dequeísmo", "queísmo", "laísmo"), return the original Spanish word exactly. Never map to religious concepts like "deism".
5. ZERO CHATTER: Output ONLY the translated list lines. No introductions, no notes, no markdown block wrappers.

FORMAT EXAMPLE:
t0 -> Translation
t1 -> Translation`;

            const result = await provider.generate(
              `Translate these anchored targets exactly:\n${chunkList}`,
              systemPrompt,
              model
            );

            // 1. Parse lines with space-resilient index token identification
            const lines = result.split("\n")
              .map(line => line.trim())
              .filter(line => /t\s*\d+\s*(?:->|◈|:|=>|=)/.test(line));

            // 2. Build the lookup map matching index values back to terms safely
            const translationMap = new Map<string, string>();
            lines.forEach(line => {
              const match = line.match(/t\s*(\d+)\s*(?:->|◈|:|=>|=)\s*(.*)/);
              if (match) {
                const idx = parseInt(match[1], 10);
                if (idx >= 0 && idx < chunk.length) {
                  let trans = match[2].trim();
                  // Strip decorative markdown wrappers from boundary lines
                  trans = trans.replace(/^[\s\_\*\`\"\'\[\]\(\)]+/, "").replace(/[\s\_\*\`\"\'\[\]\(\)]+$/, "");
                  trans = trans.replace(/[.,;]+$/, "");

                  if (trans) {
                    translationMap.set(chunk[idx].toLowerCase(), trans);
                  }
                }
              }
            });

            // 3. Map back to the chunk array using normalized lookups
            chunk.forEach((term) => {
              const translation = translationMap.get(term.toLowerCase()) || term;
              const combined = `${term}, ${translation}`;
              this.tagTranslationCache.set(term, combined);
            });

          } catch (e: unknown) {
            this.plugin.diagnosticService.report("Vault Brain", `Tag translation chunk failed: ${errorToMessage(e)}`, "warning");
            chunk.forEach(term => {
              this.tagTranslationCache.set(term, term);
            });
          }

          translatedCount += chunk.length;

          // TIME-BASED CHECKPOINT: Guarantees at least 15 seconds between disk writes.
          // This gives aggressive sync engines (iCloud/Dropbox) ample time to release 
          // file locks, entirely preventing file duplication on fast translation runs.
          const now = Date.now();
          if (now - lastSaveTime > 15000) {
            await this.saveTagCache();
            lastSaveTime = now;
          }

          // Mandatory 400ms pacing delay to clear context queue on local server instances
          await new Promise(resolve => setTimeout(resolve, 400));
        }

        // 🟢 Final guaranteed storage commit after all chunks finish
        await this.saveTagCache();
      }
    }
  }

  private translateTagsBilingually(spanishTags: string): string {
    if (!this.plugin.settings.tagShadowingEnabled || !spanishTags.trim()) return spanishTags;
    const cached = this.tagTranslationCache.get(spanishTags);
    return cached !== undefined ? cached : spanishTags;
  }


  /**
     * Samples the vault to collect representative tag path components and
     * leaf values, runs them through the translation model, and returns a
     * structured result for display in the settings panel.
     *
     * This is a READ-ONLY diagnostic operation. It does not modify the index,
     * the translation cache, or any settings.
     *
     * Returns an array of result rows, each containing:
     * - type: "path" (generic category label) or "leaf" (specific value)
     * - original: the Spanish input string
     * - translated: what the model returned, or null on failure
     * - warning: a human-readable warning if the output looks malformed
     */
  async testTagTranslation(): Promise<{
    type: "path" | "leaf";
    original: string;
    translated: string | null;
    warning: string | null;
  }[]> {
    const files = this.plugin.app.vault.getMarkdownFiles();

    // Scan vault in-memory cache to get real tags
    const uniquePaths = new Set<string>();
    const uniqueLeaves = new Set<string>();

    for (const file of files) {
      const cache = this.plugin.app.metadataCache.getFileCache(file);
      const rawTags: string[] = [];
      const add = (value: string) => {
        if (value && value.trim()) rawTags.push(value.trim());
      };

      if (cache?.tags) {
        for (const t of cache.tags) add(t.tag);
      }
      const frontmatter = cache?.frontmatter as Record<string, unknown> | undefined;
      if (frontmatter) {
        for (const tag of this.extractTagValues(frontmatter.tags)) add(tag);
        for (const tag of this.extractTagValues(frontmatter.tag)) add(tag);
      }

      for (const raw of rawTags) {
        const { path, leaf } = this.splitTagHierarchy(raw);
        if (leaf && !VaultIndexer.GENERIC_TAG_NODES.has(leaf.toLowerCase())) {
          uniqueLeaves.add(leaf);
        }
        for (const p of path) {
          if (p && !VaultIndexer.GENERIC_TAG_NODES.has(p.toLowerCase())) {
            uniquePaths.add(p);
          }
        }
      }
    }

    const pathSample = Array.from(uniquePaths).slice(0, 20);
    const leafSample = Array.from(uniqueLeaves).slice(0, 15);

    const results: {
      type: "path" | "leaf";
      original: string;
      translated: string | null;
      warning: string | null;
    }[] = [];

    if (pathSample.length === 0 && leafSample.length === 0) {
      return results;
    }

    const settings = this.plugin.settings;
    const model = settings.tagTranslationModel.trim();
    if (!model) {
      throw new Error("No Tag Translation Model configured. Set one in settings before testing.");
    }

    const provider =
      settings.tagTranslationProvider === "lmstudio"
        ? new LmStudioProvider(settings.lmStudioUrl, settings.temperature, 200)
        : new OllamaProvider(settings.ollamaBaseUrl, settings.temperature, 200);

    const runAnchoredTest = async (sample: string[], contextRule: string, type: "path" | "leaf") => {
      const chunkList = sample.map((term, index) => `t${index} -> ${term}`).join("\n");
      const systemPrompt = `You are a mechanical translation tool mapping Spanish to ${settings.tagShadowingLanguage}.
Translate ONLY the values on the right side of the -> delimiter.

CRITICAL RULES:
1. ANCHOR PRESERVATION: You MUST retain the exact token anchor identifier (e.g., t0 ->, t1 ->) on the left side of the line.
2. ZERO CHATTER: Output ONLY the translated list lines. No explanations.
3. ${contextRule}

FORMAT EXAMPLE:
t0 -> Translation
t1 -> Translation`;

      try {
        const result = await provider.generate(
          `Translate these anchored targets exactly:\n${chunkList}`,
          systemPrompt,
          model
        );

        const lines = result.split("\n")
          .map(line => line.trim())
          .filter(line => /t\s*\d+\s*(?:->|◈|:|=>|=)/.test(line));

        const translationMap = new Map<number, string>();
        lines.forEach(line => {
          const match = line.match(/t\s*(\d+)\s*(?:->|◈|:|=>|=)\s*(.*)/);
          if (match) {
            const idx = parseInt(match[1], 10);
            let trans = match[2].trim();
            trans = trans.replace(/^[\s\_\*\`\"\'\[\]\(\)]+/, "").replace(/[\s\_\*\`\"\'\[\]\(\)]+$/, "");
            trans = trans.replace(/[.,;]+$/, "");
            if (trans) {
              translationMap.set(idx, trans);
            }
          }
        });

        sample.forEach((original, i) => {
          const translated = translationMap.get(i) || null;
          results.push({
            type,
            original,
            translated,
            warning: translated ? null : "Model omitted this anchor or failed to parse."
          });
        });
      } catch (e: unknown) {
        sample.forEach(original => {
          results.push({ type, original, translated: null, warning: errorToMessage(e) });
        });
      }
    };

    if (pathSample.length > 0) {
      await runAnchoredTest(pathSample, "Translate generic category labels.", "path");
    }
    if (leafSample.length > 0) {
      await runAnchoredTest(leafSample, "Translate common nouns. Preserve proper nouns exactly.", "leaf");
    }

    return results;
  }


  private extractFrontmatterSummary(
    content: string,
    file: TFile
  ): { fullText: string; summaryOnly: string; tagsOnly: string } | null {
    const cache = this.plugin.app.metadataCache.getFileCache(file);
    const frontmatter = cache?.frontmatter as Record<string, unknown> | undefined;

    let summaryOnly = "";
    if (frontmatter) {
      const summaryKeys = ["resumen", "summary", "description", "abstract", "Resumen", "Summary"];
      for (const key of summaryKeys) {
        if (frontmatter[key] && typeof frontmatter[key] === "string") {
          summaryOnly = (frontmatter[key] as string).trim();
          break;
        }
      }
    }

    const tags = this.collectShadowTags(content, file);
    let tagsOnly = "";

    if (tags.length > 0) {
      tagsOnly = tags.map(t => this.translateTagsBilingually(t)).join(", ");
    }

    if (!summaryOnly && !tagsOnly) return null;

    const parts: string[] = [`${file.basename}`];
    if (summaryOnly) parts.push(summaryOnly);
    if (tagsOnly) parts.push("Temas: " + tagsOnly);

    if (frontmatter) {
      const authorValue = frontmatter.autor || frontmatter.Autor || frontmatter.author || frontmatter.Author;
      if (authorValue) {
        if (typeof authorValue === "string") {
          parts.push("Autor: " + authorValue.trim());
        } else if (Array.isArray(authorValue)) {
          parts.push("Autor: " + authorValue.map(a => String(a).trim()).join(", "));
        }
      }
    }

    return {
      fullText: `${getModelPrefixes(this.plugin.settings.ragEmbeddingModel).doc}${parts.join("\n")}`,
      summaryOnly,
      tagsOnly
    };
  }

  /**
   * Rebuilds the index incrementally.
   */
  async rebuildIndex() {
    if (this.isIndexing) {
      new Notice("Vault Brain: Indexing is already in progress.");
      return;
    }
    this.isIndexing = true;
    this.loadWasPartial = false; // Reset partial load flag since we are doing a full rebuild

    this.tagTranslationCache.clear();
    this.lastShardSaveTime = 0;

    try {
      this.plugin.setIndexingStatus("Initializing Index Rebuild...");

      // Decoupled Privacy Guard: Indexing is allowed if the embedding model is local (Ollama).
      // Summaries are extracted via regex (local).
      // Tag translation will be handled locally or reported as a warning if it fails.
      if (!this.plugin.settings.ragEmbeddingModel) {
        new Notice("Vault Brain: No embedding model selected.");
        return;
      }
      if (!this.plugin.settings.vaultBrainEnabled) {
        new Notice("Vault Brain: Vault Brain is disabled in settings.");
        return;
      }

      const files = this.plugin.app.vault.getMarkdownFiles();
      const total = files.length;
      console.log(`Horme Brain: Rebuilding index for ${total} files...`);

      // Purge orphaned entries for files that were deleted or renamed while inactive
      const validPaths = new Set(files.map(f => f.path));
      const knownPaths = Array.from(this.pathIndex.keys());
      for (const path of knownPaths) {
        if (!validPaths.has(path)) {
          this.removeEntriesForPath(path);
        }
      }



      let updatedCount = 0;
      let consecutiveErrors = 0;

      this.plugin.settings.indexStatus = `Indexing (0/${total})...`;
      await this.plugin.saveSettings();
      this.plugin.setIndexingStatus(`Indexing 0 / ${total}`);

      // 1. Add this right before the loop: for (let i = 0; i < total; i++) {
      await this.preTranslateTags(files);

      for (let i = 0; i < total; i++) {
        const file = files[i];

        // Update the status bar for every single file so the UI feels responsive
        this.plugin.settings.indexStatus = `Indexing (${i + 1}/${total}): ${file.name.slice(0, 20)}...`;
        this.plugin.setIndexingStatus(`Indexing ${i + 1} / ${total}`);

        const existing = this.getEntriesForPath(file.path);
        if (existing.length > 0 && existing[0].mtime >= file.stat.mtime) {
          continue;
        }

        try {
          const content = await this.plugin.app.vault.read(file);
          if (!content.trim()) {
            this.removeEntriesForPath(file.path);
            continue;
          }

          const chunksWithOffsets = this.plugin.embeddingService.chunkTextWithOffsets(content);
          const validChunks = chunksWithOffsets.filter(c => c.text.trim().length > 0);

          // 2. Remove "await" and the third parameter from this line
          const fmData = this.extractFrontmatterSummary(content, file);
          const hasFmSummary = fmData !== null;

          if (validChunks.length > 0 || hasFmSummary) {
            // Extract heading structure for heading-aware chunking
            const headings = this.extractHeadings(content);
            const bilingualTags = fmData?.tagsOnly || "";

            // Build embedding texts with search_document prefix and heading context
            const embeddingTexts = validChunks.map(c => {
              const hp = this.getHeadingPathAtOffset(headings, c.start);
              const docPrefix = getModelPrefixes(this.plugin.settings.ragEmbeddingModel).doc;
              // Prepend bilingual tags to every chunk so the vector captures both languages.
              // Tags are brief (30–80 chars) and won't dilute the body content meaningfully.
              const tagLine = bilingualTags ? `Tags: ${bilingualTags}\n` : "";
              return `${docPrefix}${file.basename}${hp ? ' > ' + hp : ''}\n${tagLine}\n${c.text}`;
            });

            // Add a dedicated frontmatter summary embedding (offset 0,0 = signals summary entry)
            if (hasFmSummary) embeddingTexts.unshift(fmData.fullText);

            const embeddings = await this.plugin.embeddingService.getEmbeddings(embeddingTexts);

            if (!embeddings || embeddings.length !== embeddingTexts.length) {
              throw new Error(`API returned ${embeddings?.length || 0} embeddings for ${embeddingTexts.length} chunks. Cancelling to prevent data loss.`);
            }

            const newEntries: IndexEntry[] = [];
            let embOffset = 0;
            if (hasFmSummary) {
              if (embeddings[0] && embeddings[0].length > 0) {
                newEntries.push({
                  path: file.path,
                  chunkStart: 0,
                  chunkEnd: 0,
                  embedding: quantizeEmbeddingToInt8(embeddings[0]),
                  mtime: file.stat.mtime,
                  summaryText: fmData.summaryOnly,
                  tagsText: fmData.tagsOnly
                });
              }
              embOffset = 1;
            }

            // Store chunk embeddings with heading path
            for (let j = 0; j < validChunks.length; j++) {
              const emb = embeddings[j + embOffset];
              if (emb && emb.length > 0) {
                const hp = this.getHeadingPathAtOffset(headings, validChunks[j].start);
                newEntries.push({
                  path: file.path,
                  chunkStart: validChunks[j].start,
                  chunkEnd: validChunks[j].end,
                  embedding: quantizeEmbeddingToInt8(emb),
                  mtime: file.stat.mtime,
                  ...(hp ? { headingPath: hp } : {}),
                  ...(bilingualTags ? { tagsText: bilingualTags } : {})
                });
              }
            }
            this.removeEntriesForPath(file.path);
            this.addEntries(newEntries);
          } else {
            this.removeEntriesForPath(file.path);
          }
          updatedCount++;
          consecutiveErrors = 0; // reset on success

          // Auto-save checkpoint with a 30-second minimum pacing to prevent progress loss and avoid cloud sync collisions
          const now = Date.now();
          if (now - this.lastShardSaveTime > 30_000) {
            await this.saveIndex();
            this.lastShardSaveTime = Date.now();
          }
        } catch (e: unknown) {
          this.plugin.diagnosticService.report("Vault Brain", `Note skipped: ${file.path} (${errorToMessage(e)})`, "warning");
          consecutiveErrors++;
          // (e.g. one bad file) should not stop the entire rebuild.
          if (consecutiveErrors > 15) {
            new HormeErrorModal(
              this.plugin.app,
              "Vault Brain: Indexing paused",
              `Indexing stopped after ${consecutiveErrors} consecutive failures. This usually means Ollama is unreachable or the embedding model is not loaded. Check that Ollama is running and that the model "${this.plugin.settings.ragEmbeddingModel}" is available.`,
              `Last error: check the developer console (Ctrl+Shift+I) for details.`
            ).open();
            this.plugin.settings.indexStatus = "Failed (too many consecutive errors)";
            await this.plugin.saveSettings();

            if (updatedCount > 0) {
              await this.saveIndex();
            }

            return;
          }
        }
      }

      await this.saveIndex();

      // Log translation results to diagnostics panel for post-rebuild audit
      if (this.tagTranslationCache.size > 0) {
        const cacheEntries = Array.from(this.tagTranslationCache.entries())
          .filter(([, v]) => v && v !== "")  // skip fallback (untranslated) entries
          .slice(0, 30);                      // cap log length

        if (cacheEntries.length > 0) {
          const logLines = cacheEntries.map(([k, v]) => `  ${k} → ${v}`).join("\n");
          this.plugin.diagnosticService.report(
            "Tag Translation",
            `Translation results (${cacheEntries.length} unique inputs):\n${logLines}`,
            "info"
          );
        }
      }

      this.plugin.settings.indexStatus = "Ready";
      await this.plugin.saveSettings();

      if (consecutiveErrors > 0) {
        new Notice(`Vault Brain: Indexed ${updatedCount} files. (Some failed — check console)`);
      } else {
        new Notice(`Vault Brain: Successfully indexed ${updatedCount} files.`);
      }
    } catch (e: unknown) {
      this.plugin.diagnosticService.report("Vault Brain", `Fatal indexing error: ${errorToMessage(e)}`);
      new HormeErrorModal(
        this.plugin.app,
        "Vault Brain: Fatal indexing error",
        "Indexing stopped due to an unexpected error. Your partial progress has been saved and the next rebuild will resume from where it left off.",
        errorToMessage(e)
      ).open();
    } finally {
      // Acquire the queue lock BEFORE releasing isIndexing to prevent a race
      // where an event-triggered enqueueIndex() calls processQueue() concurrently
      // with the post-rebuild queue drain below.
      const hasQueuedWork = this.indexingQueue.length > 0;
      if (hasQueuedWork) this.isProcessingQueue = true;

      this.isIndexing = false;
      this.plugin.setIndexingStatus(null);

      // Process any files that were modified and queued while the rebuild was running
      if (hasQueuedWork) {
        // isProcessingQueue is already true, so processQueue() will skip its own guard.
        // We drive the loop manually here and release the lock in the finally below.
        try {
          // Release the flag so processQueue() can acquire it normally
          this.isProcessingQueue = false;
          await this.processQueue();
        } catch (e) {
          this.isProcessingQueue = false;
          this.plugin.diagnosticService.report("Vault Brain", `Post-rebuild queue failed: ${errorToMessage(e)}`, "warning");
        }
      }
    }
  }

  private indexingQueue: TFile[] = [];
  isProcessingQueue = false;

  /**
   * Enqueues a file for indexing.
   */
  async enqueueIndex(file: TFile) {
    const canIndex = this.plugin.isLocalProviderActive() || this.plugin.settings.allowCloudRAG;
    if (!canIndex || !this.plugin.settings.vaultBrainEnabled) {
      return;
    }
    // Incremental indexing is only allowed after at least one successful full build.
    if (!(await this.hasBuiltIndex())) {
      return;
    }

    console.log(`Horme Brain: Enqueueing ${file.path} for indexing...`);
    if (!this.indexingQueue.some(f => f.path === file.path)) {
      this.indexingQueue.push(file);
    }
    void this.processQueue().catch(e => {
      this.plugin.diagnosticService.report("Vault Brain", `Queue processing failed: ${errorToMessage(e)}`, "warning");
    });
  }

  private async processQueue() {
    // Prevent queue processing if a full rebuild is currently active
    if (this.isProcessingQueue || this.isIndexing) return;
    this.isProcessingQueue = true;

    // Wait for the index to finish loading from disk before processing any changes.
    // If we process and save a partial index during startup, we risk overwriting
    // the full shard files with only the freshly modified notes.
    if (!this.isLoaded) {
      this.plugin.setIndexingStatus("Waiting for brain index...");
      const deadline = Date.now() + 5000;
      while (!this.isLoaded && Date.now() < deadline) {
        await new Promise<void>(r => window.setTimeout(r, 100));
      }
      if (!this.isLoaded) {
        console.error("Horme Brain: Index failed to load within timeout. Aborting queue to prevent data loss.");
        this.plugin.diagnosticService.report("Vault Brain", "Queue aborted: Index failed to load after 5s timeout.", "error");
        this.plugin.setIndexingStatus("Index load timeout");
        this.isProcessingQueue = false;
        return;
      }
    }

    try {
      // Guard: if the index loaded only partially, incremental saves are blocked
      // (saveIndex refuses to write). Warn the user instead of silently discarding work.
      if (this.loadWasPartial) {
        console.warn("Horme Brain: Skipping queue — index loaded partially. Rebuild to restore.");
        this.plugin.diagnosticService.report(
          "Vault Brain",
          "Incremental indexing skipped: index loaded partially. Please rebuild the Vault Brain to restore full functionality.",
          "warning"
        );
        this.isProcessingQueue = false;
        return;
      }

      let totalQueued = this.indexingQueue.length;
      let processed = 0;

      // Ensure queued files have tags pre-translated to avoid mid-queue VRAM swaps
      if (totalQueued > 0) {
        await this.preTranslateTags([...this.indexingQueue]);
      }

      while (this.indexingQueue.length > 0) {
        // Re-check on every iteration — provider may have changed since enqueue
        const canStillIndex = this.plugin.isLocalProviderActive() || this.plugin.settings.allowCloudRAG;
        if (!canStillIndex || !this.plugin.settings.vaultBrainEnabled) {
          console.log("Horme Brain: Provider changed during queue processing. Clearing queue.");
          this.indexingQueue = [];
          break;
        }

        totalQueued = Math.max(totalQueued, processed + this.indexingQueue.length);
        const file = this.indexingQueue.shift();
        if (file) {
          processed++;
          this.plugin.setIndexingStatus(`Indexing ${processed} / ${totalQueued}`);

          const didWork = await this.indexFile(file);

          // Only yield 50ms if heavy LLM work was actually done.
          // Otherwise, yield 0ms just to let the DOM repaint the status bar.
          if (didWork) {
            await new Promise<void>(r => window.setTimeout(r, 50));
          } else if (processed % 50 === 0) {
            await new Promise<void>(r => window.setTimeout(r, 0));
          }
        }
      }

      // Save once when the queue is fully drained instead of after every file.
      // This eliminates repeated synchronous JSON.stringify calls that block typing.
      if (processed > 0) {
        this.plugin.setIndexingStatus("Saving brain index...");
        await this.saveIndex();
      }
    } finally {
      this.isProcessingQueue = false;
      this.plugin.setIndexingStatus(null);
    }
  }

  /**
   * Indexes a single file (Internal use by queue or rebuild).
   * Returns true if the file was embedded, false if skipped.
   */
  private async indexFile(file: TFile): Promise<boolean> {
    try {
      // Crucial mtime check to prevent redundant re-indexing of unchanged files
      const existing = this.getEntriesForPath(file.path);
      if (existing.length > 0 && existing[0].mtime >= file.stat.mtime) {
        return false;
      }

      const content = await this.plugin.app.vault.read(file);
      if (!content.trim()) {
        this.removeEntriesForPath(file.path);
        return false;
      }

      const chunksWithOffsets = this.plugin.embeddingService.chunkTextWithOffsets(content);
      const validChunks = chunksWithOffsets.filter(c => c.text.trim().length > 0);

      // Remove "await" and the third parameter from this line
      const fmData = this.extractFrontmatterSummary(content, file);
      const hasFmSummary = fmData !== null;

      if (validChunks.length > 0 || hasFmSummary) {
        const headings = this.extractHeadings(content);
        const bilingualTags = fmData?.tagsOnly || "";

        const embeddingTexts = validChunks.map(c => {
          const hp = this.getHeadingPathAtOffset(headings, c.start);
          const docPrefix = getModelPrefixes(this.plugin.settings.ragEmbeddingModel).doc;
          // Prepend bilingual tags to every chunk so the vector captures both languages.
          // Tags are brief (30–80 chars) and won't dilute the body content meaningfully.
          const tagLine = bilingualTags ? `Tags: ${bilingualTags}\n` : "";
          return `${docPrefix}${file.basename}${hp ? ' > ' + hp : ''}\n${tagLine}\n${c.text}`;
        });

        if (hasFmSummary) embeddingTexts.unshift(fmData.fullText);

        const embeddings = await this.plugin.embeddingService.getEmbeddings(embeddingTexts);

        if (!embeddings || embeddings.length !== embeddingTexts.length) {
          throw new Error(`API returned ${embeddings?.length || 0} embeddings for ${embeddingTexts.length} chunks. Cancelling to prevent data loss.`);
        }

        const newEntries: IndexEntry[] = [];
        let embOffset = 0;
        if (hasFmSummary) {
          if (embeddings[0] && embeddings[0].length > 0) {
            newEntries.push({
              path: file.path,
              chunkStart: 0,
              chunkEnd: 0,
              embedding: quantizeEmbeddingToInt8(embeddings[0]),
              mtime: file.stat.mtime,
              summaryText: fmData.summaryOnly,
              tagsText: fmData.tagsOnly
            });
          }
          embOffset = 1;
        }

        for (let j = 0; j < validChunks.length; j++) {
          const emb = embeddings[j + embOffset];
          if (emb && emb.length > 0) {
            const hp = this.getHeadingPathAtOffset(headings, validChunks[j].start);
            newEntries.push({
              path: file.path,
              chunkStart: validChunks[j].start,
              chunkEnd: validChunks[j].end,
              embedding: quantizeEmbeddingToInt8(emb),
              mtime: file.stat.mtime,
              ...(hp ? { headingPath: hp } : {}),
              ...(bilingualTags ? { tagsText: bilingualTags } : {})
            });
          }
        }
        this.removeEntriesForPath(file.path);
        this.addEntries(newEntries);
        return true;
      } else {
        this.removeEntriesForPath(file.path);
        return false;
      }
    } catch (e: unknown) {
      this.plugin.diagnosticService.report("Vault Brain", `Auto-index failed for ${file.path}: ${errorToMessage(e)}`, "warning");
      return false;
    }
  }

  private static normalizeTextForSearch(text: string): string {
    return text
      .toLowerCase()
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "");
  }

  /**
   * Multi-query hybrid search using vector similarity + keyword boosting.
   * Uses nomic-embed-text search_query prefix and dual-embedding fusion.
   */
  async search(query: string, topN = 20): Promise<string[]> {
    console.log(`Horme Brain: Search called. Index size: ${this.index.length}`);
    const canAccess = this.plugin.isLocalProviderActive() || this.plugin.settings.allowCloudRAG;
    if (!this.plugin.settings.vaultBrainEnabled || !canAccess) {
      if (!canAccess) this.plugin.diagnosticService.report("Horme Privacy Guard", "Vault search blocked (Cloud Provider Active & allowCloudRAG is OFF).", "warning");
      return [];
    }

    // Wait for the index to finish loading from disk before searching.
    // The constructor calls loadIndex() fire-and-forget, so an early search
    // (e.g. immediately after plugin load) might otherwise see an empty index.
    if (!this.isLoaded) {
      const deadline = Date.now() + 5000;
      while (!this.isLoaded && Date.now() < deadline) {
        await new Promise<void>(r => window.setTimeout(r, 100));
      }
      if (!this.isLoaded) {
        this.plugin.diagnosticService.report("Horme Brain", "Index not yet loaded, skipping search.", "warning");
        return [];
      }
    }

    try {
      // 1. Refine query: remove conversational junk (Bilingual)
      const refinedQuery = query.toLowerCase()
        // Step 1: strip well-known leading conversational prefixes
        .replace(
          /^(?:ayúdame a encontrar|podrías ayudarme a encontrar|busca|encuentra|dime sobre|háblame de|tienes algo sobre|algún artículo sobre|alguna nota sobre|is it true that|can you help me find|tell me about|do you have anything on|search for|find|look for|i read that|i heard that|i was told that|can you confirm that|is it correct that|did you know that)\s+/i,
          ""
        )
        // Step 2: strip trailing conversational question closers
        .replace(/\?+$/, "")
        .replace(/\s*(?:right\?|correct\?|is that right|is that true|can you confirm)\s*$/i, "")
        .trim();

      // 1.5 Extract quoted terms for exact-match priority (normalized for accent-insensitivity)
      const normalizedQueryForQuotes = VaultIndexer.normalizeTextForSearch(query);
      const quotedMatches = normalizedQueryForQuotes.match(/"([^"]+)"/g) || [];
      const quotedTerms = quotedMatches.map(m => m.replace(/"/g, ""));

      // Normalize refined query for robust keyword splitting (stripping accents)
      const normalizedRefinedQuery = VaultIndexer.normalizeTextForSearch(refinedQuery);
      const cleanedQuery = normalizedRefinedQuery.replace(/[.,/#!$%^&*;:{}=\-_`~()]/g, " ");
      const searchTerms = cleanedQuery.split(/\s+/).filter(t => t.length > 2);

      // 2. Truncate very long queries (e.g. user pasting whole articles) to a
      //    focused portion for embedding — models work best with focused queries.
      //    We keep the first 500 chars, which captures the topic without dilution.
      const MAX_EMBED_CHARS = 500;
      const embeddingQuery = refinedQuery.length > MAX_EMBED_CHARS
        ? refinedQuery.slice(0, MAX_EMBED_CHARS)
        : refinedQuery;

      // 3. Multi-query: full (truncated) query + keyword-distilled variant.
      // If Ollama rejects or times out (any error, not just "context length"),
      // fall back to keyword-only scoring instead of returning zero results.
      const { query: qPrefix } = getModelPrefixes(this.plugin.settings.ragEmbeddingModel);
      let primaryEmbedding: number[] = [];
      let secondaryEmbedding: number[] | null = null;

      try {
        primaryEmbedding = await this.plugin.embeddingService.getEmbedding(`${qPrefix}${embeddingQuery}`);
        const keyTerms = searchTerms.filter(t => t.length > 3).join(' ');
        if (keyTerms && keyTerms !== embeddingQuery) {
          secondaryEmbedding = await this.plugin.embeddingService.getEmbedding(`${qPrefix}${keyTerms}`);
        }
      } catch {
        // Embedding failed (Ollama down, model not loaded, long-text timeout, etc.)
        // Log and continue with vector scores zeroed out — keyword bonus alone will
        // Still surface obvious matches like the exact-title case.
        this.plugin.diagnosticService.report("Search", "Embedding failed. Falling back to keyword search.", "warning");
      }

      const MIN_SIMILARITY = 0.10; // Lowered: keyword-only searches can still score ~0.25+

      // 4. Score all entries: max(primary, secondary) + metadata bonus
      const rawScored = this.index
        .map(entry => {
          const emb = typeof entry.embedding === "string"
            ? decompressEmbeddingToInt8(entry.embedding)
            : entry.embedding;

          const primaryScore =
            primaryEmbedding.length > 0 ? cosineSimilarityFloatInt8(primaryEmbedding, emb) : 0;
          const secondaryScore = secondaryEmbedding ? cosineSimilarityFloatInt8(secondaryEmbedding, emb) : 0;
          const vectorScore = Math.max(primaryScore, secondaryScore);

          // Metadata keyword boosting: Exact quotes (Major) + Regular terms (Minor) (Accent-insensitive!)
          let metadataBonus = 0;
          const lowerPath = VaultIndexer.normalizeTextForSearch(entry.path);
          const lowerSummary = VaultIndexer.normalizeTextForSearch(entry.summaryText || "");
          const lowerTags = VaultIndexer.normalizeTextForSearch(entry.tagsText || "");
          const lowerHeading = VaultIndexer.normalizeTextForSearch(entry.headingPath || "");

          // 1. Quoted terms get a massive priority boost
          for (const term of quotedTerms) {
            if (
              lowerPath.includes(term) ||
              lowerSummary.includes(term) ||
              lowerTags.includes(term) ||
              lowerHeading.includes(term)
            ) {
              metadataBonus += 0.15;
            }
          }

          // 2. Regular keyword boosting, skipping stop-words
          for (const term of searchTerms) {
            if (STOP_WORDS.has(term)) continue;
            if (lowerPath.includes(term)) metadataBonus += 0.05;
            if (lowerSummary.includes(term)) metadataBonus += 0.04;
            if (lowerTags.includes(term)) metadataBonus += 0.03;
            if (lowerHeading.includes(term)) metadataBonus += 0.04;
          }

          // Cap the metadata bonus so it doesn't exponentially drown out semantic vector scores
          metadataBonus = Math.min(metadataBonus, this.plugin.settings.searchMetadataCap);

          return { entry, score: vectorScore + metadataBonus };
        })
        .filter(s => s.score >= MIN_SIMILARITY)
        .sort((a, b) => b.score - a.score);

      // 4.1 Content-Aware Boosting (The "Deep Scan")
      // Fetch and scan actual chunk text for top candidates to reward factual matches.
      const topCandidates = rawScored.slice(0, 50); // Cap deep scan to prevent memory exhaustion
      const scored: Array<{ entry: IndexEntry; score: number }> = [];
      const fileCache = new Map<string, string>(); // Cache content to avoid redundant reads for the same file

      for (const item of topCandidates) {
        let contentBonus = 0;
        try {
          let content = fileCache.get(item.entry.path);
          if (content === undefined) {
            const abstractFile = this.plugin.app.vault.getAbstractFileByPath(item.entry.path);
            if (abstractFile instanceof TFile) {
              content = await this.plugin.app.vault.read(abstractFile);
              fileCache.set(item.entry.path, content);
            }
          }

          if (content) {
            const chunkText = item.entry.chunkStart === 0 && item.entry.chunkEnd === 0
              ? ((item.entry.summaryText || item.entry.tagsText)
                ? ((item.entry.summaryText || "") + " " + (item.entry.tagsText || ""))
                : content.slice(0, 800))
              : content.slice(item.entry.chunkStart, item.entry.chunkEnd);

            const normalizedChunkText = VaultIndexer.normalizeTextForSearch(chunkText);

            // Boost for search terms found in the actual body text (Accent-insensitive!)
            for (const term of searchTerms) {
              if (STOP_WORDS.has(term)) continue;
              if (normalizedChunkText.includes(term)) {
                contentBonus += 0.05; // Significant reward for factual body match
              }
            }
            // Extra boost for quoted terms in content
            for (const term of quotedTerms) {
              if (normalizedChunkText.includes(term)) contentBonus += 0.15;
            }
          }
        } catch { /* skip if file read fails */ }

        scored.push({
          entry: item.entry,
          score: item.score + Math.min(contentBonus, this.plugin.settings.searchContentCap)
        });
      }

      // Re-sort after content boosting
      scored.sort((a, b) => b.score - a.score);

      // Diversity Injection: for each summary entry, ensure the best content
      // chunk from the same note is promoted to follow it immediately.
      const injected: Array<{ entry: IndexEntry; score: number }> = [];

      for (const item of scored) {
        if (injected.length >= topN * 2) break; // cap the injection pass
        if (!injected.includes(item)) {
          injected.push(item);
        }

        if (item.entry.chunkStart === 0 && item.entry.chunkEnd === 0) {
          // This is a summary entry — find the best sibling content chunk
          const bestContent = scored.find(
            s => s.entry.path === item.entry.path
              && !(s.entry.chunkStart === 0 && s.entry.chunkEnd === 0)
              && !injected.includes(s)
          );
          if (bestContent) {
            injected.push(bestContent);
          }
        }
      }

      // Replace `scored` with the injection-ordered list
      // (the takeUpTo dedup below still applies, so no duplicates will
      // survive into `selected`)
      const diverseScored = injected;

      // 4.5 File-level dedup: prevent a single long note from flooding the top-N.
      // Pass 1: take max 1 chunk per file for variety.
      // Pass 2: if we still have capacity, allow up to 3 chunks per file.
      const selected: Array<{ entry: IndexEntry; score: number }> = [];
      const perFileCounts = new Map<string, number>();

      const takeUpTo = (maxChunksPerFile: number) => {
        for (const item of diverseScored) {
          if (selected.length >= topN) return;
          const current = perFileCounts.get(item.entry.path) || 0;
          if (current >= maxChunksPerFile) continue;
          if (selected.includes(item)) continue; // CRITICAL DEDUP FIX
          perFileCounts.set(item.entry.path, current + 1);
          selected.push(item);
        }
      };

      takeUpTo(1);
      if (selected.length < topN) takeUpTo(3);

      // 5. Fetch content for top results
      const results: string[] = [];
      console.log(
        `%cHorme Brain: Top ${selected.length} search results:`,
        "color: #34d399; font-weight: bold;"
      );
      selected.forEach((s, idx) => {
        console.log(
          `  %c${idx + 1}. [Score: ${s.score.toFixed(3)}]%c ${s.entry.path}${s.entry.headingPath ? " > " + s.entry.headingPath : ""
          }`,
          "color: #34d399; font-weight: bold;",
          "color: inherit;"
        );
      });

      for (const { entry } of selected) {
        try {
          const abstractFile = this.plugin.app.vault.getAbstractFileByPath(entry.path);
          if (!(abstractFile instanceof TFile)) continue;

          let content = fileCache.get(entry.path);
          if (content === undefined) {
            content = await this.plugin.app.vault.read(abstractFile);
            fileCache.set(entry.path, content);
          }

          let chunk: string;
          if (entry.chunkStart === 0 && entry.chunkEnd === 0) {
            const parts: string[] = [];
            if (entry.summaryText) parts.push(entry.summaryText);
            if (entry.tagsText) parts.push("Topics: " + entry.tagsText);
            // Fallback: if no structured summary was stored, use first 600 chars
            // but strip the frontmatter block first.
            if (parts.length === 0) {
              chunk = content.replace(/^---[\s\S]*?---\s*/m, "").slice(0, 600).trim();
            } else {
              chunk = parts.join("\n");
            }
          } else {
            chunk = content.slice(entry.chunkStart, entry.chunkEnd).trim();
          }

          const heading = entry.headingPath ? ` (${entry.headingPath})` : "";
          if (chunk) results.push(`[From ${entry.path}${heading}]:\n${chunk}`);
        } catch {
          // File deleted or unreadable — skip silently
        }
      }

      return results;
    } catch (e: unknown) {
      console.error("Horme: Search failed", e);
      this.plugin.diagnosticService.report("Search", `Search failed: ${errorToMessage(e)}`);
      return [];
    }
  }
  /**
   * Retrieves semantically related notes for the active file.
   * Useful for the "Connections" side panel.
   */
  async getConnections(activeFilePath: string): Promise<{ path: string, score: number }[] | null | undefined> {
    if (!this.plugin.settings.vaultBrainEnabled || !this.isLoaded) return null;

    const sourceEntries = this.getEntriesForPath(activeFilePath);
    if (!sourceEntries || sourceEntries.length === 0) return undefined;

    // Parse excluded folders
    const excludedPrefixes = this.plugin.settings.connectionsExcludedFolders
      .split(",")
      .map(s => s.trim())
      .filter(s => s.length > 0);

    // Find the most representative embedding for the file.
    // Prefer the summary entry (chunkStart: 0) or fallback to the first content chunk.
    const representativeEntry = sourceEntries.find(e => e.chunkStart === 0 && e.chunkEnd === 0) || sourceEntries[0];

    const sourceEmb = typeof representativeEntry.embedding === "string"
      ? decompressEmbeddingToInt8(representativeEntry.embedding)
      : representativeEntry.embedding;

    const pathScores = new Map<string, number>();

    for (const entry of this.index) {
      if (entry.path === activeFilePath) continue; // Skip source file

      // Check exclusions
      if (excludedPrefixes.some(prefix => entry.path.startsWith(prefix))) {
        continue;
      }

      const emb = typeof entry.embedding === "string"
        ? decompressEmbeddingToInt8(entry.embedding)
        : entry.embedding;

      const score = cosineSimilarityInt8(sourceEmb, emb);

      const currentMax = pathScores.get(entry.path) || 0;
      if (score > currentMax) {
        pathScores.set(entry.path, score);
      }
    }

    return Array.from(pathScores.entries())
      .map(([path, score]) => ({ path, score }))
      .filter(s => s.score >= this.plugin.settings.connectionsThreshold)
      .sort((a, b) => b.score - a.score)
      .slice(0, this.plugin.settings.connectionsMaxResults);
  }
}
